/* STAR WARS: Hyperspace Assault — © 2026 Fahath Richvi. All rights reserved. See LICENSE. */
/* Locations, campaign missions, objectives, enemy waves and radio chatter */
(function () {
  /* ======================= LOCATIONS ======================= */
  SW.ENVS = {
    kessra: {
      key: 'kessra', name: 'Kessra Belt — Outer Rim',
      sky: { seed: 11, c1: [170, 40, 120], c2: [60, 40, 190] },
      sun: { dir: [-0.35, 0.42, -0.84] },
      planet: { type: 'gas', palette: 'amber', seed: 21, R: 4300, pos: [-12000, -5000, 22000], ring: true },
      station: true,
      asteroids: { mode: 'ring', count: 70, mat: 'rock' },
    },
    hothar: {
      key: 'hothar', name: 'Hothar — Frozen World',
      sky: { seed: 23, c1: [70, 130, 210], c2: [150, 180, 235], dust: [140, 160, 200] },
      sun: { dir: [0.45, 0.35, -0.82], color: 0xdde8ff, glow: [4.2, 5, 6], halo: [0.6, 0.75, 1.0], intensity: 1.9 },
      hemi: [0x5a7aa8, 0x1a2230],
      planet: { type: 'ice', seed: 5, R: 5200, pos: [9000, -6000, 20000] },
      moon: { type: 'dead', seed: 44, R: 900, pos: [-6000, 3500, 16000] },
      asteroids: { mode: 'ring', count: 60, mat: 'ice' },
      dust: 0xbfd8ff,
    },
    yavara: {
      key: 'yavara', name: 'Yavara — Jungle World',
      sky: { seed: 31, c1: [80, 60, 170], c2: [40, 100, 170] },
      sun: { dir: [-0.5, 0.35, -0.8] },
      planet: { type: 'forest', seed: 8, R: 4800, pos: [-11000, -4000, 21000], clouds: true },
      moon: { type: 'gas', palette: 'rust', seed: 9, R: 2400, pos: [9000, 5000, 24000] },
      station: true,
      asteroids: { mode: 'ring', count: 50, mat: 'rock' },
    },
    moraxa: {
      key: 'moraxa', name: 'Moraxa Debris Field — Shattered World',
      sky: { seed: 41, c1: [170, 70, 40], c2: [90, 50, 50], dust: [170, 130, 110] },
      sun: { dir: [0.3, 0.3, -0.9], color: 0xffb080, glow: [6, 3, 1.4], halo: [1.2, 0.5, 0.25], size: 1.4 },
      hemi: [0x6a4030, 0x100806],
      planet: { type: 'dead', seed: 14, R: 3600, pos: [7000, 3000, 19000], ring: true, ringTint: 0xc09070 },
      asteroids: { mode: 'none' },
      dust: 0xd0a080,
    },
    aquilon: {
      key: 'aquilon', name: 'Aquilon — Ocean World',
      sky: { seed: 52, c1: [40, 160, 160], c2: [40, 80, 170] },
      sun: { dir: [-0.2, 0.5, -0.84], color: 0xfff6e0 },
      planet: { type: 'ocean', seed: 12, R: 6000, pos: [-8000, -7000, 18000], clouds: true },
      moon: { type: 'dead', seed: 3, R: 700, pos: [5000, 2500, 12000] },
      asteroids: { mode: 'ring', count: 30, mat: 'rock' },
    },
    vulkar: {
      key: 'vulkar', name: 'Vulkar — Volcanic World',
      sky: { seed: 63, c1: [200, 70, 30], c2: [120, 30, 50], dust: [190, 110, 90] },
      sun: { dir: [0.4, 0.25, -0.88], color: 0xff9a70, glow: [6, 2.4, 1.0], halo: [1.3, 0.4, 0.2], size: 1.6 },
      hemi: [0x803020, 0x200805],
      planet: { type: 'lava', seed: 27, R: 5000, pos: [-9000, -6000, 17000] },
      asteroids: { mode: 'ring', count: 60, mat: 'dark' },
      dust: 0xff9a70,
    },
    tashar: {
      key: 'tashar', name: 'Tashar — Twin-Sun Desert World',
      sky: { seed: 71, c1: [160, 110, 60], c2: [90, 60, 120] },
      sun: { dir: [-0.3, 0.3, -0.9], color: 0xfff0c8 },
      sun2: { dir: [-0.05, 0.42, -0.9], color: 0xffb070, glow: [5, 3, 1.5], intensity: 1.1 },
      hemi: [0x806040, 0x201008],
      planet: { type: 'desert', seed: 19, R: 5400, pos: [8000, -6500, 18000] },
      moon: { type: 'dead', seed: 61, R: 800, pos: [-7000, 2000, 15000] },
      asteroids: { mode: 'ring', count: 40, mat: 'red' },
    },
    glacius: {
      key: 'glacius', name: 'Glacius Ring — Ice Giant',
      sky: { seed: 83, c1: [120, 200, 230], c2: [60, 100, 180], dust: [150, 190, 220] },
      sun: { dir: [0.5, 0.45, -0.75], color: 0xe6f2ff, glow: [4.5, 5, 6], intensity: 1.6 },
      hemi: [0x5a8ab0, 0x10202a],
      planet: { type: 'gas', palette: 'cyan', seed: 33, R: 6200, pos: [-10000, -2000, 21000], ring: true, ringTint: 0xcfe8ff, atmo: 0xbfeaff },
      asteroids: { mode: 'none' },
      dust: 0xd0ecff,
    },
    toxara: {
      key: 'toxara', name: 'Toxara — Poisoned World',
      sky: { seed: 94, c1: [90, 170, 60], c2: [40, 110, 100], dust: [140, 170, 110] },
      sun: { dir: [-0.4, 0.4, -0.82], color: 0xf0ffd0 },
      hemi: [0x507a30, 0x101a06],
      planet: { type: 'toxic', seed: 45, R: 5200, pos: [10000, -5000, 19000] },
      asteroids: { mode: 'ring', count: 50, mat: 'dark' },
    },
    crimson: {
      key: 'crimson', name: 'The Crimson Void — Red Giant',
      sky: { seed: 105, c1: [190, 40, 60], c2: [110, 40, 150] },
      sun: { dir: [0.2, 0.2, -0.96], color: 0xff7050, glow: [6, 1.8, 1.0], halo: [1.4, 0.3, 0.2], size: 3.2, intensity: 2.8 },
      hemi: [0x702040, 0x100410],
      planet: { type: 'gas', palette: 'purple', seed: 57, R: 5600, pos: [-10000, 3000, 20000], ring: true, ringTint: 0xd0a0ff, atmo: 0xc890ff },
      asteroids: { mode: 'ring', count: 50, mat: 'red' },
    },
    sylvara: {
      key: 'sylvara', name: 'Sylvara — Forest Moon',
      sky: { seed: 116, c1: [60, 90, 170], c2: [120, 60, 150] },
      sun: { dir: [-0.3, 0.5, -0.8] },
      planet: { type: 'gas', palette: 'amber', seed: 66, R: 9000, pos: [14000, 4000, 26000], ring: false },
      moon: { type: 'forest', seed: 70, R: 2600, pos: [-5000, -3500, 11000], clouds: true },
      asteroids: { mode: 'ring', count: 40, mat: 'rock' },
    },
    veil: {
      key: 'veil', name: 'The Veiled Nebula',
      sky: { seed: 127, c1: [200, 60, 160], c2: [80, 40, 160], neb: 2 },
      sun: { dir: [0.1, 0.8, -0.5], color: 0xffc8f0, intensity: 1.6 },
      hemi: [0x803070, 0x200818],
      fog: { color: 0x2a0f2e, density: 0.00085 },
      asteroids: { mode: 'ring', count: 90, mat: 'dark' },
      dust: 0xff90e0,
    },
    imperialis: {
      key: 'imperialis', name: 'Imperialis — Throne World',
      sky: { seed: 138, c1: [60, 70, 140], c2: [40, 40, 80], neb: 0.5, band: 0.7 },
      sun: { dir: [-0.6, 0.35, -0.72], color: 0xfff0e0, intensity: 2.2 },
      planet: { type: 'city', seed: 81, R: 6500, pos: [-6000, -9000, 16000] },
      asteroids: { mode: 'none' },
    },
  };

  /* ======================= CAMPAIGN ======================= */
  SW.MISSIONS = [
    {
      title: 'OPERATION FIRST LIGHT', sub: 'Mission 1 — Kessra Outer Belt', env: 'kessra', type: 'kills',
      briefing: 'An Imperial TIE patrol is sweeping the Kessra asteroid belt, hunting our supply convoys. Red Squadron will drop out of hyperspace on their flank. Engage and destroy every fighter before they can report our position to the fleet.',
      objectives: [{ type: 'kills', count: 10, text: 'Destroy 10 TIE Fighters' }],
      wingmen: ['RED TWO', 'RED THREE'],
      waves: [{ spawn: [['tie', 5]] }, { spawn: [['tie', 5]], when: 2 }],
      intro: [['RED LEADER', 'Red Squadron, lock S-foils in attack position. Here they come!'], ['RED TWO', 'I see them — five TIEs, dead ahead.']],
      torps: 6,
    },
    {
      title: 'OPERATION IRON VEIL', sub: 'Mission 2 — Orbit of Hothar', env: 'hothar', type: 'kills',
      briefing: 'Above the frozen world of Hothar, the Empire is escorting a fleet tender with TIE Interceptors — faster, deadlier and better armed than standard TIEs. Break their screen. Watch your shields and lead your shots; these pilots are the best the Empire has.',
      objectives: [{ type: 'kills', count: 16, text: 'Destroy 16 Imperial fighters' }],
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR'],
      waves: [
        { spawn: [['tie', 4], ['interceptor', 2]] },
        { spawn: [['interceptor', 3], ['tie', 2]], when: 2 },
        { spawn: [['interceptor', 3], ['tie', 2]], when: 2 },
      ],
      intro: [['RED LEADER', 'Interceptors inbound. Stay sharp, Red Squadron.'], ['RED FOUR', "They're fast... I can barely track them!"]],
      torps: 6,
    },
    {
      title: 'OPERATION SHATTERED CROWN', sub: 'Mission 3 — Assault on the Dominion', env: 'yavara', type: 'capital',
      briefing: 'The Imperial Star Destroyer DOMINION is jumping into orbit over Yavara to crush our base. Its turbolasers will tear apart any capital ship we send — but a fighter strike can cripple it. Destroy the two SHIELD GENERATOR domes atop the command tower, then take out the BRIDGE. Use proton torpedoes on the key targets.',
      objectives: [{ type: 'shields', text: 'Destroy the shield generators' }, { type: 'bridge', text: 'Destroy the command bridge' }],
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR', 'GOLD FIVE'],
      waves: [{ spawn: [['tie', 4]] }],
      capital: {},
      intro: [['REBEL COMMAND', 'Red Squadron, sensors show a massive ship dropping out of hyperspace!', 'command']],
      torps: 10,
    },
    {
      title: 'OPERATION ROCKFALL', sub: 'Mission 4 — Escape the Moraxa Debris Field', env: 'moraxa', type: 'asteroidRun',
      briefing: 'Red Squadron has been ambushed near the shattered world of Moraxa. The only way out is straight through the debris field to our hyperspace beacon on the far side. The rocks are dense, some are drifting, and more are falling in from the planet\'s broken crust. Fly fast, blast small rocks out of your way — and do NOT hit the big ones.',
      objectives: [{ type: 'reach', text: 'Reach the hyperspace beacon' }],
      timeLimit: 150,
      timeoutText: 'The Imperial fleet closed the net before you escaped the field.',
      field: { count: 340, mat: 'rock', box: { x: 700, y: 420, z0: -1650, z1: 2100 }, goalZ: 2450, debrisRate: 1.4 },
      start: [0, 0, -2000], arena: 5200,
      wingmen: ['RED TWO'],
      waves: [{ spawn: [['tie', 3]], at: 15, behind: true }, { spawn: [['tie', 3]], at: 60, behind: true }],
      intro: [['RED LEADER', "Into the field, everyone. Follow the beacon — and watch those rocks!"], ['R2 UNIT', '*nervous warble* Beacon locked. Distance 4.4 kilometres.', 'command']],
      torps: 6,
      outro: 'You threaded the Moraxa debris field and jumped to safety. Few pilots could fly like that.',
    },
    {
      title: 'OPERATION LIFELINE', sub: 'Mission 5 — Escort over Aquilon', env: 'aquilon', type: 'escort',
      briefing: 'Three Rebel medical transports are evacuating wounded from the ocean world of Aquilon. They are slow and lightly armed, and TIE squadrons are already vectoring in to intercept. Protect the transports until they reach their jump point. At least TWO must make it out.',
      objectives: [{ type: 'escort', need: 2, text: 'Protect the transports until they jump' }],
      transports: { count: 3, need: 2, speed: 26, hp: 650, shield: 250, names: ['TRANSPORT BRIGHT HOPE', 'TRANSPORT SOLACE', 'TRANSPORT DAWNSTAR'], startZ: -1100, destZ: 1800 },
      transportAggro: 0.55,
      wingmen: ['RED TWO', 'RED THREE'],
      waves: [
        { spawn: [['tie', 4]], at: 6 },
        { spawn: [['tie', 3], ['interceptor', 1]], when: 2 },
        { spawn: [['tie', 4], ['interceptor', 2]], when: 2 },
        { spawn: [['interceptor', 3], ['tie', 3]], when: 2 },
      ],
      loopFrom: 2,
      intro: [['TRANSPORT BRIGHT HOPE', 'Red Squadron, we are glad to see you. Beginning our run to the jump point.'], ['RED LEADER', 'Stay close to the transports. Nothing gets through.']],
      torps: 8,
      outro: 'The medical transports made the jump. Hundreds of lives were saved today because of you.',
    },
    {
      title: 'OPERATION EMBERFALL', sub: 'Mission 6 — Silence the Vulkar Relays', env: 'vulkar', type: 'relays',
      briefing: 'Above the volcanic world of Vulkar, the Empire operates three hyperwave COMMUNICATION RELAYS that coordinate its patrols across the sector. Each relay is guarded by defense turrets and a TIE garrison. Destroy all three transmitter arrays to blind the Imperial fleet.',
      objectives: [{ type: 'relays', count: 3, text: 'Destroy the communication relays' }],
      relays: [[-650, 60, 350], [600, -90, 800], [-100, 140, 1500]],
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR'],
      waves: [
        { spawn: [['tie', 4]] },
        { spawn: [['tie', 3], ['interceptor', 2]], when: 1 },
        { spawn: [['interceptor', 3], ['tie', 2]], when: 1 },
      ],
      loopFrom: 1,
      intro: [['RED LEADER', 'Relay stations on scope. Take out the transmitter dishes on top of each tower.'], ['R2 UNIT', '*beep* Relay targets marked.', 'command']],
      torps: 8,
      outro: 'The Vulkar relays are silent. The Imperial patrols in this sector are flying blind.',
    },
    {
      title: 'BOSS: THE BLACK WING', sub: 'Mission 7 — Duel over Tashar', env: 'tashar', type: 'ace', boss: true,
      briefing: 'Intelligence has identified INQUISITOR VEYL, the Empire\'s deadliest ace, flying a prototype TIE ADVANCED with deflector shields. Veyl has destroyed eleven of our starfighters. Under the twin suns of Tashar we will draw Veyl out with a decoy convoy. Clear the escort, then take the Inquisitor down. Expect Veyl to call in reinforcements when wounded.',
      objectives: [{ type: 'kills', count: 5, text: 'Clear the TIE escort' }, { type: 'boss', text: 'Defeat Inquisitor Veyl' }],
      bossDef: { name: 'INQUISITOR VEYL', hp: 900, shield: 350 },
      wingmen: ['RED TWO', 'RED THREE'],
      waves: [{ spawn: [['tie', 5]] }, { boss: true, spawn: [['interceptor', 2]], when: 0 }],
      intro: [['RED LEADER', 'Twin suns in your eyes, Red Squadron. Watch for the black TIE.']],
      torps: 8,
      outro: 'Inquisitor Veyl is gone. The Empire has lost its greatest pilot — and you have earned a legend.',
    },
    {
      title: 'OPERATION WHITE SILENCE', sub: 'Mission 8 — The Glacius Ice Ring', env: 'glacius', type: 'asteroidRun',
      briefing: 'A squadron of TIE Interceptors is hunting you through the ice rings of Glacius. Our extraction beacon is on the far side of the ring. The ice is dense and the ring is collapsing — chunks are tumbling across the lane. Outfly the Interceptors, break through the ice and jump out.',
      objectives: [{ type: 'reach', text: 'Break through the ice ring to the beacon' }],
      timeLimit: 140,
      timeoutText: 'The Interceptor squadron boxed you in before you reached the beacon.',
      field: { count: 380, mat: 'ice', box: { x: 650, y: 380, z0: -1650, z1: 2150 }, goalZ: 2500, debrisRate: 0.9 },
      start: [0, 0, -2000], arena: 5200,
      wingmen: ['RED TWO'],
      waves: [{ spawn: [['interceptor', 3]], at: 8, behind: true }, { spawn: [['interceptor', 3]], at: 45, behind: true }, { spawn: [['interceptor', 2], ['tie', 2]], at: 85, behind: true }],
      intro: [['RED LEADER', "Interceptors on our six! Into the ice — they won't follow us for long."]],
      torps: 6,
      outro: 'You broke through the collapsing ice ring. The Interceptors that followed you in never came out.',
    },
    {
      title: 'OPERATION CONVOY BREAKER', sub: 'Mission 9 — Toxara Supply Line', env: 'toxara', type: 'convoy',
      briefing: 'Three Imperial bulk FREIGHTERS are hauling weapons out of the Toxara refineries. If they reach their jump point, those weapons will be used against our fleet. Intercept the convoy and destroy the freighters. We can afford to let ONE escape — no more.',
      objectives: [{ type: 'convoy', need: 2, text: 'Destroy the Imperial freighters' }],
      transports: { count: 3, need: 2, speed: 22, hp: 800, shield: 200, names: ['FREIGHTER ORE-7', 'FREIGHTER ORE-12', 'FREIGHTER ORE-19'], startZ: 400, destZ: 3000, imperial: true },
      arena: 3800,
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR'],
      waves: [
        { spawn: [['tie', 4]] },
        { spawn: [['tie', 3], ['interceptor', 2]], when: 2 },
        { spawn: [['interceptor', 3], ['tie', 2]], when: 2 },
      ],
      loopFrom: 1,
      intro: [['RED LEADER', 'Convoy sighted, heading for the jump point. Hit the freighters hard — torpedoes work well on those hulls.']],
      torps: 10,
      outro: 'The weapons convoy is scrap. The Empire will feel that loss on every front.',
    },
    {
      title: 'BOSS: THE TYRANT', sub: 'Mission 10 — Dreadnought in the Crimson Void', env: 'crimson', type: 'capital', boss: true,
      briefing: 'The Empire has unleashed the DREADNOUGHT TYRANT — a war-machine twice the size of a Star Destroyer, guarded by FOUR shield generators and a forest of turbolasers. It is heading for our fleet anchorage in the Crimson Void. Take down all four shield generators, then destroy the bridge. This is the most dangerous target we have ever faced.',
      objectives: [{ type: 'shields', text: 'Destroy the 4 shield generators' }, { type: 'bridge', text: 'Destroy the Dreadnought bridge' }],
      capital: { scale: 2.4, shields: 4, shieldHp: 420, bridgeHp: 1600, name: 'DREADNOUGHT "TYRANT"', boss: true, tint: 0x8f949c, moreTurrets: true, maxFighters: 8, launch: ['tie', 'interceptor', 'interceptor'] },
      capitalPos: [0, -80, 1200],
      arena: 3000,
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR', 'GOLD FIVE'],
      waves: [{ spawn: [['interceptor', 3], ['tie', 2]] }],
      intro: [['REBEL COMMAND', "Here it comes. By the Force... it's enormous.", 'command']],
      torps: 14,
      outro: 'The Tyrant burns in the light of the red giant. The Empire\'s mightiest warship is no more.',
    },
    {
      title: 'OPERATION HOLD THE LINE', sub: 'Mission 11 — Defense of Sylvara', env: 'sylvara', type: 'survival',
      briefing: 'Our new base on the forest moon of Sylvara is still powering up its planetary shield. The Empire has sent everything it has in orbit to stop it. Hold the line in orbit for THREE MINUTES until the shield comes online. The waves will keep coming — and they will get bigger.',
      objectives: [{ type: 'survive', time: 180, text: 'Hold the line until the shield is online' }],
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR'],
      survival: true,
      intro: [['BASE COMMAND', 'Shield generator charging. We need three minutes, Red Leader!', 'command']],
      torps: 10,
      outro: "Sylvara's planetary shield is online. The base is safe — thanks to Red Squadron.",
    },
    {
      title: 'OPERATION NIGHTSHADE', sub: 'Mission 12 — Ambush in the Veiled Nebula', env: 'veil', type: 'kills',
      briefing: 'An Imperial hunter squadron is hiding inside the Veiled Nebula, ambushing any ship that passes. Sensors are nearly blind in the gas clouds — you will only see them when they are close. Trust your radar, stay with your wingmen and destroy the hunters.',
      objectives: [{ type: 'kills', count: 18, text: 'Destroy 18 hunters in the nebula' }],
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR'],
      waves: [
        { spawn: [['interceptor', 3], ['tie', 2]] },
        { spawn: [['interceptor', 3], ['tie', 3]], when: 1 },
        { spawn: [['interceptor', 4], ['tie', 3]], when: 1 },
      ],
      intro: [['RED LEADER', "Can't see a thing out here. Watch your scopes."], ['RED THREE', 'Contacts... they just vanished again!']],
      torps: 8,
      outro: 'The hunters of the Veiled Nebula have been hunted. The trade lanes are open again.',
    },
    {
      title: 'FINAL BOSS: HEART OF THE EMPIRE', sub: 'Mission 13 — The Battle Station', env: 'imperialis', type: 'station', boss: true,
      briefing: 'This is it. The Empire\'s new BATTLE STATION is orbiting the throne world and its superlaser is charging to destroy our fleet. Knock out the FOUR SUPERLASER EMITTERS around the dish, then fire PROTON TORPEDOES into the THERMAL EXHAUST PORT on the equatorial trench — lasers cannot penetrate it. If the countdown reaches zero, the fleet is lost. May the Force be with you.',
      objectives: [{ type: 'emitters', text: 'Destroy the 4 superlaser emitters' }, { type: 'port', text: 'Torpedo the thermal exhaust port' }],
      countdown: 300,
      timeoutText: 'The superlaser fired. The Rebel fleet has been destroyed.',
      stationPos: [0, 0, 1900], arena: 4500, start: [0, 120, -1400],
      wingmen: ['RED TWO', 'RED THREE', 'RED FOUR', 'GOLD FIVE'],
      waves: [{ spawn: [['tie', 3], ['interceptor', 2]] }],
      intro: [['REBEL COMMAND', 'All wings report in. Superlaser charging — you have five minutes.', 'command'], ['RED LEADER', 'Red Leader standing by. Let\'s end this.']],
      torps: 14,
      outro: 'The battle station is destroyed. The Empire\'s ultimate weapon is gone — and the galaxy is free. You are a hero of the Rebellion.',
      final: true,
    },
    {
      title: 'ENDLESS: LAST STAND', sub: 'Survival — How long can you hold the line?', env: 'random', type: 'endless',
      briefing: 'The Empire has committed everything it has left. Wave after wave of TIE fighters and Interceptors are inbound. There is no retreat. Survive as long as you can and rack up the highest score in the galaxy.',
      objectives: [{ type: 'endless', text: 'Survive the endless Imperial assault' }],
      wingmen: ['RED TWO', 'RED THREE'],
      waves: [],
      intro: [['RED LEADER', "This is it, everyone. They're coming in waves. Hold the line!"]],
      torps: 8,
    },
  ];

  SW.BOSS_TAUNTS = {
    arrive: ['So, the Rebels send their best. How disappointing.', 'I have been waiting for you, Red Leader.'],
    phase: ['Impressive. Most impressive. But you cannot win alone.', 'Squadron — to me! Destroy them!', 'You will not escape the dark side!'],
    death: ['No... this is not... possible...'],
  };

  SW.CHATTER = {
    rebelKill: ['Got one!', 'Splash one TIE!', "He's gone!", 'Great shot!', "That's another one down!", 'Scratch one!', 'Yahoo! Nice flying!', 'Direct hit!'],
    playerKill: ["Great shot, Leader! That's one in a million!", 'Nice shooting, Red Leader!', 'Good kill, Leader!', 'You got him!', "He didn't stand a chance!", 'Great flying, Leader!'],
    wingHurt: ["I'm hit! I'm hit! Shields holding...", "Get him off me! I can't shake him!", 'Taking fire! Somebody help!', "I've got one on my tail!", 'Losing power to my rear deflector!'],
    wingLost: ["I can't hold it! Ahhh—", 'Eject! Eject— *static*', "I'm going down!"],
    playerHurt: ["Leader, you've got one on your tail!", 'Watch yourself, Leader!', "Red Leader, you're taking fire!"],
    empire: ['All TIE units, converge on the lead X-wing.', 'Rebel scum. Cut them down.', 'Close formation. Do not let them escape.', 'Target their astromech units.'],
    lowHull: ['*frantic beeping* Hull integrity critical!', '*worried whistle* Hull is failing, pull back!'],
    transportHit: ['We are taking heavy fire! Requesting assistance!', 'Shields failing — get these TIEs off us!', 'They are all over us, Red Squadron!'],
    debris: ['Incoming debris! Watch it!', 'Rocks inbound — dodge!', 'Look out, big one coming through!'],
  };
})();
